trigger:
- main

pr: 
- main

stages:
  - stage: 'Test'
    jobs:
    - job: RunTests
      pool:
        vmImage: ubuntu-20.04
      strategy:
        matrix:
          Python3.6:
            python.version: '3.6'
        maxParallel: 3
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(python.version)
        displayName: 'Setup Python'
      - script: |
          pip install virtualenv
          virtualenv .venv
        displayName: 'Create Venv'
      - script: |
          source .venv/bin/activate 
          ./run setup
        displayName: 'Setup development environment'
      - script: | 
          source .venv/bin/activate 
          ./run check -f
        displayName: 'Check formatting'
      - script: |   
          source .venv/bin/activate 
          ./run test all unit
        displayName: 'Run Unit tests'
