trigger:
  - main

# no PR triggers: only committers to the main branch should be able to trigger these builds
pr: 
  - main

stages:
  - stage: 'Test'
    jobs:
    - job: RunTests
      pool:
        vmImage: ubuntu-20.04
        strategy:
          matrix:
            Python3.7:
              python.version: '3.7'
            Python3.8:
              python.version: '3.8'
            Python3.9:
              python.version: '3.9'
          maxParallel: 3
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(python.version)
        displayName: 'Setup Python'
      - script: |
        virtualenv venv
        source venv/bin/activate
        # Setup development environment
        ./run setup
        # Check formatting
        ./run check -f
        # Run Unit tests
        ./run test
        displayName: 'Install dependencies'
        displayName: 'Unit test'

      - script: |
          python -m pip install -r docs/requirements.txt
          export PYTHONPATH=$(pwd)
          cd docs/
          make clean
          make html 2>&1 | tee tmp_log
          if [[ $(grep -c "WARNING:" tmp_log) != 0 ]]; then echo "found warnings"; grep "WARNING:" tmp_log; exit 1; fi
        displayName: 'Build Docs'