trigger:
- main

pr: 
- main

stages:
  - stage: 'Test'
    jobs:
    - job: RunTests
      pool:
        vmImage: ubuntu-20.04
      strategy:
        matrix:
          # Python3.7:
          #   python.version: '3.7'
          Python3.8:
            python.version: '3.8'
          # Python3.9:
          #   python.version: '3.9'
        maxParallel: 3
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(python.version)
        displayName: 'Setup Python'
      - script: |
          pip install virtualenv
          virtualenv venv
        displayName: 'Create Venv'
      - script: |
          source venv/bin/activate 
          ./run setup
        displayName: 'Setup development environment'
      - script: | 
          source venv/bin/activate 
          ./run check -f
        displayName: 'Check formatting'
      - script: |   
          source venv/bin/activate 
          ./run test
        displayName: 'Install dependencies'
      - script: |
          python -m pip install -r docs/requirements.txt
          export PYTHONPATH=$(pwd)
          cd docs/
          make clean
          make html 2>&1 | tee tmp_log
          if [[ $(grep -c "WARNING:" tmp_log) != 0 ]]; then echo "found warnings"; grep "WARNING:" tmp_log; exit 1; fi
        displayName: 'Build Docs'